### ISSUE TITLE
Classe PedidoVenda

### ISSUE THREAD

**Issue by profRenatoOliveira1** [LuisEduSouza/projeto-elitecar-servidor#2]
Luis, na sua classe PedidoVenda, coloque o nome do atributo que vai gerenciar o ID do pedido como idPedido para mantermos o padrão.

Não que o que você fez esteja errado, não está, seu sistema iria funcionar normalmente, mas só pra gente seguir um padrão.

**Comment by LuisEduSouza** [comment]
Feito

**Comment by profRenatoOliveira1** [comment]
muito bem.
